### PR TITLE
Implement flags to control retry delays

### PR DESCRIPTION
**Pull request by hansmi**
Add two new flags, "--proxy.retry.initial-wait" and
"--proxy.retry.max-wait", controlling how long to sleep after
encountering a proxy poll failure (i.e. network timeout). An
exponential, randomized backoff algorithm is used to prevent thundering
herds. Discussed in prometheus-community/PushProx#82.

### CODE REVIEW

**Comment by SuperQ** [comment]
In order to add the new external package, you will need to include the go modules and `go mod vendor` changes.

**Comment by hansmi** [comment]
> […] you will need to include the go modules and `go mod vendor` changes.

Of course. I somehow missed them in my `git add`. Also updated the commit message with more details.

**Comment by SuperQ** [comment]
You can now rebase against head with the removed vendor dir.

**Comment by hansmi** [comment]
@SuperQ done, rebased on top of `master`.

**Review by SuperQ — APPROVED** [review]
LGTM, Thanks

**Pull request merged**
